import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header'
import Sidenav from '@/components/sidenav'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import ReactQueryProviders from '@/providers/react-query-provider'
import MobileNav from '@/components/mobile-nav'
import ConfirmationDialog from '@/components/confirmation-dialog'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="sm:h-screen sm:overflow-hidden">
				<ReactQueryProviders>
					<ReactQueryDevtools
						initialIsOpen={false}
						buttonPosition="top-right"
					/>
					<div className="flex h-full flex-col sm:flex-row">
						<Sidenav />
						<main className="flex w-full flex-col px-2 py-2 pb-16 sm:px-8 sm:py-4 sm:pb-2">
							<Header />
							{children}
						</main>
						<MobileNav />
					</div>
					<ConfirmationDialog />
				</ReactQueryProviders>
			</body>
		</html>
	)
}
