import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header'
import Sidenav from '@/components/sidenav'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import ReactQueryProviders from '@/providers/react-query-provider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="sm:h-screen sm:overflow-hidden">
				<ReactQueryProviders>
					<ReactQueryDevtools initialIsOpen={false} />
					<div className="flex h-full">
						<Sidenav />

						<main className="flex w-full flex-col px-2 py-2 sm:px-8 sm:py-4">
							<Header />
							{children}
						</main>
					</div>
				</ReactQueryProviders>
			</body>
		</html>
	)
}
